### ISSUE TITLE
Required MaxQuant version and legacy file support

### ISSUE THREAD

**Issue by straussmaximilian** [MannLabs/alphaviz#2]
Hi,
alphaviz is looking very nice and I am excited about this project.

###  Describe the bug
I encountered a couple of bugs which I think are related to a mismatch in MaxQuant and file versions.

### Old files
I tried to look at the sample files from the [Online-PASEF-Paper](https://pubmed.ncbi.nlm.nih.gov/30385480/). When using the installer version 0.0.1 I get an `ModuleNotFoundError` for `lfz` (see Screenshot). Most likely this is due the files being older and not having the legacy support alphatims version when compiling the installer.

I then installed version 0.0.2 from dev and installed `python-lfz`. I can upload the data, however will get a `ValueError` when reading the evidence. Most likely this is as previous MaxQuant versions did not report `Mass deviations [Da]` (see Screenshot).

### MaxQuant version
I did rerun our AlphaPept IRT and later also the HeLa sample with MaxQuant version 1.6.14.0. In both cases I get `ValueError` as 'Gene names' are not in the list. I was using the default MaxQuant settings - am I missing an option here or maybe using the wrong MaxQuant version?

### Potential solutions
- For the legacy support we could use alphatims with legacy support. Or we could state which files are supported.
- For the ValueErrors we could check if the columns exists and only use them if they do. Another option would be to define which MaxQuant version with what settings are required.

Please let me know if I was missing any documentation regarding this and I hope this is helpful. Looking forward to get it to run it and test further.

![Screenshot 2021-11-08 at 11 31 07](https://user-images.githubusercontent.com/16521288/140784218-88cb8cc8-e108-4ed3-b09b-ac2ff4555c0e.png)
![Screenshot 2021-11-08 at 13 02 59](https://user-images.githubusercontent.com/16521288/140784701-bc6fa045-a996-450d-be23-bb1bd119e428.png)
![Screenshot 2021-11-08 at 13 42 22](https://user-images.githubusercontent.com/16521288/140784936-76d65787-4f66-4a44-8994-b36d1f489ed1.png)

**Comment by EugeniaVoytik** [comment]
Hi Max, 

This bug should be fixed in the new AlphaVis release (v. 1.0.5). I have tested it with the outputs of different versions of MQ and everything looks fine. If you could check if this bug is still reproducible, that would be very helpful! 

Best
Jane

**Comment by straussmaximilian** [comment]
Hi,
Very excited to try the new release.

I just did a quick run with the latest MaxQuant Version (2.0.3.0) with the Bruker HeLa testfile. Unfortunately, after uploading I get an error:
![Screen Shot 2022-01-27 at 4 45 54 PM](https://user-images.githubusercontent.com/16521288/151393075-79f1f43f-df17-4be0-aafb-9b1318e11c17.png)

I did copy the files on your pool folder in case you want to investigate. 
![Screen Shot 2022-01-27 at 4 44 42 PM](https://user-images.githubusercontent.com/16521288/151393307-92d3687a-7cc1-4dc6-8393-e7f854b2e217.png)

Will run with some older versions and get back to you!

**Comment by straussmaximilian** [comment]
I now checked 1.6.14.0, same Error. Tracing the bug it seems it is accessing some fields that do not exist in the proteinGroup. They are listed in a MaxQuant documentation (http://www.coxdocs.org/doku.php?id=maxquant:table:proteingrouptable) from 2015. Maybe this was exported for some older versions? Or maybe do i need to activate something in MaxQuant? I was using the standard settings.

**Comment by EugeniaVoytik** [comment]
Hi Max,

Thank you very much for your example file. It helped a lot to understand why you are getting the error message. For this implementation, I was mainly concentrating on cases where users have multiple samples in an analysed experiment. In this case the proteinGroups.txt table has a special column <"Peptides " + exp> where you can get information about all the peptides that have been identified in the current sample of the experiment. When the user only has one sample file, things work a little differently, and I hope I have fixed that at this point. I've tested a new released version (1.0.6) with the file you provided. I hope everything works now, and thanks for testing the tool!

Best
Jane

**Comment by straussmaximilian** [comment]
Hi Jane,

now it works! Thanks.
